export const TechStackData = [
  { name: "HTML5", image: "/HTML.png" },
  { name: "CSS3", image: "/CSS.png" },
  { name: "JavaScript", image: "/Javascript.png" },
  { name: "ReactJS", image: "/ReactJs.png" },
  { name: "NextJS", image: "/NextJS.png" },
  { name: "NodeJS", image: "/NodeJs.png" },
  { name: "ExpressJS", image: "/expressjs-light.png" },
  { name: "Typescript", image: "/Typescript.png" },
  { name: "Supabase", image: "/Supabase.png" },
  { name: "MySQL", image: "/MySQL.png" },
  { name: "jQuery", image: "/Jquery.png" },
  { name: "GitHub", image: "/github.png" },
  { name: "Git", image: "/Vector.png"},
  { name: "PostgreSQL", image: "/PostgreSQL.png" },
];
